### ISSUE TITLE
usage to replace pug addWith

### ISSUE THREAD

**Issue by jeromew** [pugjs/babel-plugin-transform-with#2]
while working on https://github.com/pugjs/pug-code-gen/issues/21, I have been trying to use this plugin to replace the addWith feature of pug at the AST level.

There are 2 things that are not clear to me :

1/ If I use the plugin on a code block where no global is found, then it seems to leave the prelude intact while I would have expected the plugin to remove it

If i did not make a mistake,

```
// @with
{
  locals || {};
  { var a = 1; }
}

```

outputs

```
  locals || {};
  { var a = 1; }

```

but the leading expression should maybe be removed when it is not used (?)

2/ the generated code is

```
(function (console, str) {
  console.log(str);
})("console" in _ref ?....

```

when pug has something like

```
(function (console, str) {
  console.log(str);
}).call(this, "console" in _ref ?

```

I suspect that forcing the bind on `this` was done for some reason but I do not know.

**Comment by TimothyGu** [comment]
1. `locals || {}` is not side-effect-free since `locals` was not declared in the code (as determined by Babel's [`isPure`](https://github.com/babel/babel/blob/beda884f4147d7c25d341a93aa0d77211f276518/packages/babel-traverse/src/scope/index.js#L563-L601) function)
2. The `this` binding is automatic through Babel's `shadow` function property, which is implemented as an [internal plugin](https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/internal-plugins/shadow-functions.js). Try writing some code with `this` and you'll see that a `_this` variable is declared outside of the function.

**Comment by jeromew** [comment]
Thanks for the response. I feel like I enter a new land as babels internals are totally new to me and a bit ... huge ;-)

ok I understand point 2. and saw `_this` appear which I understand.

regarding point 1. do you mean that the expression `locals` could have a side-effect ? It probably can by a mechanism that I do not grasp. In that case, the old `with(locals || {})` can be understood to have the same side effect so it would make sense to keep it.

I ask these questions because I try to keep the generated AST as close as I can to the original pug generated js and these 2 things appeared.

Regarding the `locals || {}` maybe the plugin will remove them if I create the surrounding `function(locals) {}` beforehand. I'll try that.

**Comment by TimothyGu** [comment]
> Regarding the `locals || {}` maybe the plugin will remove them if I create the surrounding `function(locals) {}` beforehand. I'll try that.

Yeah, that's how it should work. As to why this is Babel's behavior, I can't say I am too sure about that; but if a variable is global, then it could have a side effect if a getter is assigned. Consider for example the following (albeit unlikely) case:

``` js
var counter = 0;
Object.defineProperty(window, 'locals', {
  get() {
    counter++;
    return {};
  }
});

with (locals || {}) {
  var a = 0;
}

console.log(counter);
```

If `locals || {}` is just removed then `counter` would equal 0, instead of the expected 1.

**Comment by jeromew** [comment]
Yes that makes sense. I'll try with the surrounding function to see what happens.

can I ask you why you wrote 2 different implementations of with as per

> For the with module, you can now either use the new (not-yet-published) https://github.com/pugjs/with, which takes a Babylon AST, or https://github.com/pugjs/babel-plugin-transform-with.

what differences do you see in them since from my quick reading the babel version of `with` does not make use of `babel-plugin-transform-with` which surprises me given the non trivial implementations of both

**Comment by TimothyGu** [comment]
`with` uses Babylon directly and is quite a bit faster (since it uses the lightweight [babylon-walk](https://github.com/pugjs/babylon-walk) instead of the heavyweight babel-traverse, and changes the source code directly instead of mutating the AST then regenerating the source). And it seems like I misspoke about `with` taking a Babylon AST -- it doesn't, taking a string as input instead.

`babel-plugin-transform-with` is more complete (handles not only `return`s but also `break`s, `continue`s, `yield`s, and `await`s), but is a lot slower.

**Comment by jeromew** [comment]
@TimothyGu I managed to use `babel-plugin-transform-with` inside the ast based `pug-code-gen` but I run into 1 last issue with a test case.

The template is

```
mixin my-mixin(arg1, arg2, arg3, arg4)
  p= arg1
  p= arg2
  p= arg3
  p= arg4


+my-mixin('1','2','3','4')

```

And the generated code is

```
function helloWorld(locals) {
  var pug_html = "",
      pug_mixins = {},
      pug_interp;

  var _ref = locals || {};

  (function (arg2, arg3, arg4) {
    var pug_indent = [];

    pug_mixins["my-mixin"] = pug_interp = function (arg1,  arg2,  arg3,  arg4) {
      var block = this && this.block,
          attributes = this && this.attributes || {};
      pug_html = pug_html + "\n";
      pug_html = pug_html + pug_indent.join("");
      pug_html = pug_html + "\u003Cp\u003E" + pug.escape(null == (pug_interp = arg1) ? "" : pug_interp) + "\u003C\u002Fp\u003E\n";
      pug_html = pug_html + pug_indent.join("");
      pug_html = pug_html + "\u003Cp\u003E" + pug.escape(null == (pug_interp = arg2) ? "" : pug_interp) + "\u003C\u002Fp\u003E\n";
      pug_html = pug_html + pug_indent.join("");
      pug_html = pug_html + "\u003Cp\u003E" + pug.escape(null == (pug_interp = arg3) ? "" : pug_interp) + "\u003C\u002Fp\u003E\n";
      pug_html = pug_html + pug_indent.join("");
      pug_html = pug_html + "\u003Cp\u003E" + pug.escape(null == (pug_interp = arg4) ? "" : pug_interp) + "\u003C\u002Fp\u003E";
    };

    pug_indent.push("");
    pug_mixins["my-mixin"]('1', '2', '3', '4');
    pug_indent.pop();
  })("arg2" in _ref ? _ref.arg2 : typeof arg2 !== "undefined" ? arg2 : undefined, "arg3" in _ref ? _ref.arg3 : typeof arg3 !== "undefined" ? arg3 : undefined, "arg4" in _ref ? _ref.arg4 : typeof arg4 !== "undefined" ? arg4 : undefined);

  ;
  return pug_html;
}
```

can that be a bug with `babel-plugin-transform-with` or is it related to the mention that "Supports arguments (unlikely to be supported)" is not supported ?

it seems that arg2, arg3 and arg4 are wrongly considered globals while arg1 is correctly not considered as global.

I tried to look at the code but must admit that I am not babel proficient enough at this stage to understand where these vars are missed (on the basis where I would be correct when saying they're missed)

**Comment by jeromew** [comment]
note that it may be related to a problem in my AST. when I try to create a test case for the module (starting from source code as string) the library correcly detects the globals. I will keep you posted.

**Comment by jeromew** [comment]
OK. Sorry for the noise here. I had a bug where I forgot to trim arg names. Leading spaces on identifiers were leading to the problem.
So it seems all pug tests pass now :-)
thanks
